### PR TITLE
Adding more image extensions

### PR DESCRIPTION
**Pull request by TheCamilovisk**
Hi @Cartucho!

I'm adding more image extension options to load. The dictionary model was chosen to make it easier to select and add more extensions.

### CODE REVIEW

**Comment by Cartucho** [comment]
Hello @TheCamilovisk ! Sorry for the delayed response, I've been on vacation. I will review the code.

**Comment by TheCamilovisk** [comment]
Hi @Cartucho! Do not worry! I was wondering if there is another way of implementing that idea, so I closed the request. But feel free to review! Thank you!

**Comment by Cartucho** [comment]
@TheCamilovisk I found both the new features very interesting. Do you think we can separate the two commits into two separate PR's? Like this one would be just about the image extensions and then there would be another one for the squared bounding boxes?

**Comment by TheCamilovisk** [comment]
Hi @Cartucho! About the image loading, I think you're right. It' a nice and simple solution. I don't know if it would be any problem with other file types, but I did not find any problems.
About the square box feature, I'll create another PR for this!

Thanks for you time!

**Comment by Cartucho** [comment]
According to OpenCV's [imread docs](https://docs.opencv.org/trunk/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56):

> If the image cannot be read (because of missing file, improper permissions, unsupported or invalid format), the function returns an empty matrix ( Mat::data==NULL ).

So we can use this :+1:

**Pull request closed without merging**
