### PR TITLE
Quick deletion via right click

### PR DESCRIPTION
**Pull request by AlexeyGy**
Hi,

thanks for your labeller for YOLO! Especially for my imprecise mouse movements, I wanted a quick way to delete some boxes and added mouse right click to do this (was not assigned before).

Cheers,
Alexey

### CODE REVIEW

**Comment by Cartucho** [comment]
Hello, thank you!
Quick question which OS are you using Windows? And what OpenCV version?

**Comment by AlexeyGy** [comment]
Thanks for answering! I am using Ubuntu 17.10 and opencv 3.1

**Comment by Cartucho** [comment]
@AlexeyGy Sorry for the delay (I was on vacation), I am testing this now.

**Comment by Cartucho** [comment]
An amazing feature! Thank you! :1st_place_medal:

**Pull request merged**
