### PR TITLE
Export a package of input & output for yolo_darknet training

### PR DESCRIPTION
**Pull request by jamietownsend**
Merge conflicts resolved

### CODE REVIEW

**Comment by Cartucho** [comment]
Hello! Thanks, so the export is a way to copy the files automatically to the `yolo_darknet` folder and set things up for training?

**Comment by jamietownsend** [comment]
Exactly. It collects the images and annotations together with the obj.names file as required to use https://github.com/AlexeyAB/darknet

**Comment by jamietownsend** [comment]
Hi Cartucho, any advance on this one?

**Comment by Cartucho** [comment]
Hello, I like the idea and I think we should merge it, however, we need to add some flexibility for other future types of exports.

I think we should use two parameters:
`python main.py --export [export_type] [export_dir_path]`

Because one does not export to `darknet` necessarily, they could be using `darkflow` for example and in this case the files to be copied are the `.xml`files instead of the `.txt`

Additionally, `elif pressed_key == ord('x'):` should only be triggered if the person indeed activated the `--export` flag.

**Pull request closed without merging**
